services:
  # A Next.js web service
  - type: web
    name: openhour
    env: node
    plan: free # Change to paid plans as needed
    region: ohio # Choose your preferred region
    buildCommand: npm install && npm run build
    startCommand: bash ./render-startup.sh
    healthCheckPath: /api/health
    healthCheckTimeout: 60 # seconds
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: openhour-db
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        value: https://openhour.onrender.com # Will be your app's URL on Render

databases:
  # Create a Postgres database
  - name: openhour-db
    plan: free
    ipAllowList: [] # Allow all connections
